#!/bin/bash

# Build script for QuickBasket extension
# Injects environment variables into extension-config.js

set -e

echo "Building QuickBasket Extension..."

# Load environment variables
if [ ! -f .env ]; then
    echo ".env not found!"
    exit 1
fi

source .env

# Validate required variables
if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_ANON_KEY" ]; then
    echo "Missing required environment variables in .env"
    echo "   Required: SUPABASE_URL, SUPABASE_ANON_KEY"
    exit 1
fi

# Set API base URL (localhost for now).
API_BASE_URL=${API_BASE_URL:-"http://127.0.0.1:8000"}

# Create extension-config.js from template
echo "Generating extension-config.js..."

cat > extension/extension-config.js << EOF
// AUTO-GENERATED - DO NOT EDIT MANUALLY
// This file is generated by build-extension.sh from extension-config.template.js

const EXT_CONFIG = {
  SUPABASE_URL: "${SUPABASE_URL}",
  SUPABASE_ANON_KEY: "${SUPABASE_ANON_KEY}",
  API_BASE_URL: "${API_BASE_URL}",
};

if (typeof module !== "undefined" && module.exports) {
  module.exports = EXT_CONFIG;
}
EOF

echo "Extension config generated successfully!"
echo ""
echo "Configuration:"
echo "  SUPABASE_URL: ${SUPABASE_URL}"
echo "  API_BASE_URL: ${API_BASE_URL}"
echo ""
echo "Extension ready to load in Chrome!"