"""init schema

Revision ID: 0f1b070fe3c3
Revises:
Create Date: 2026-01-29 01:45:17.232148

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0f1b070fe3c3"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "tracked_products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("marketplace", sa.String(length=32), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=True),
        sa.Column("external_id", sa.String(length=128), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tracked_products_canonical_url"),
        "tracked_products",
        ["canonical_url"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tracked_products_external_id"),
        "tracked_products",
        ["external_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tracked_products_marketplace"),
        "tracked_products",
        ["marketplace"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tracked_products_user_id"),
        "tracked_products",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "ai_insights",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tracked_product_id", sa.Integer(), nullable=False),
        sa.Column("insight_type", sa.String(length=64), nullable=False),
        sa.Column(
            "content_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tracked_product_id"], ["tracked_products.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_insights_tracked_product_id"),
        "ai_insights",
        ["tracked_product_id"],
        unique=False,
    )
    op.create_table(
        "price_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tracked_product_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("old_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("new_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tracked_product_id"], ["tracked_products.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_price_events_tracked_product_id"),
        "price_events",
        ["tracked_product_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_price_alerts_url"), table_name="price_alerts")
    op.drop_table("price_alerts")
    op.add_column(
        "price_snapshots", sa.Column("tracked_product_id", sa.Integer(), nullable=False)
    )
    op.add_column(
        "price_snapshots", sa.Column("raw_price_text", sa.Text(), nullable=True)
    )
    op.add_column(
        "price_snapshots",
        sa.Column("availability", sa.String(length=32), nullable=True),
    )
    op.add_column(
        "price_snapshots", sa.Column("source", sa.String(length=32), nullable=False)
    )
    op.alter_column(
        "price_snapshots",
        "price",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(precision=12, scale=2),
        existing_nullable=True,
    )
    op.alter_column(
        "price_snapshots", "currency", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "price_snapshots",
        "fetched_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_price_snapshots_marketplace"), table_name="price_snapshots")
    op.drop_index(op.f("ix_price_snapshots_url"), table_name="price_snapshots")
    op.create_index(
        op.f("ix_price_snapshots_tracked_product_id"),
        "price_snapshots",
        ["tracked_product_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "price_snapshots",
        "tracked_products",
        ["tracked_product_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("price_snapshots", "title")
    op.drop_column("price_snapshots", "url")
    op.drop_column("price_snapshots", "marketplace")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "price_snapshots",
        sa.Column("marketplace", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "price_snapshots",
        sa.Column("url", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "price_snapshots",
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "price_snapshots", type_="foreignkey")
    op.drop_index(
        op.f("ix_price_snapshots_tracked_product_id"), table_name="price_snapshots"
    )
    op.create_index(
        op.f("ix_price_snapshots_url"), "price_snapshots", ["url"], unique=False
    )
    op.create_index(
        op.f("ix_price_snapshots_marketplace"),
        "price_snapshots",
        ["marketplace"],
        unique=False,
    )
    op.alter_column(
        "price_snapshots",
        "fetched_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "price_snapshots", "currency", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "price_snapshots",
        "price",
        existing_type=sa.Numeric(precision=12, scale=2),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.drop_column("price_snapshots", "source")
    op.drop_column("price_snapshots", "availability")
    op.drop_column("price_snapshots", "raw_price_text")
    op.drop_column("price_snapshots", "tracked_product_id")
    op.create_table(
        "price_alerts",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("url", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "target_price",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("triggered", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("price_alerts_pkey")),
    )
    op.create_index(op.f("ix_price_alerts_url"), "price_alerts", ["url"], unique=False)
    op.drop_index(op.f("ix_price_events_tracked_product_id"), table_name="price_events")
    op.drop_table("price_events")
    op.drop_index(op.f("ix_ai_insights_tracked_product_id"), table_name="ai_insights")
    op.drop_table("ai_insights")
    op.drop_index(op.f("ix_tracked_products_user_id"), table_name="tracked_products")
    op.drop_index(
        op.f("ix_tracked_products_marketplace"), table_name="tracked_products"
    )
    op.drop_index(
        op.f("ix_tracked_products_external_id"), table_name="tracked_products"
    )
    op.drop_index(
        op.f("ix_tracked_products_canonical_url"), table_name="tracked_products"
    )
    op.drop_table("tracked_products")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
