"""final_baseline

Revision ID: 44fe727e2b2a
Revises:
Create Date: 2026-02-04 00:18:08.081886

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "44fe727e2b2a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "tracked_products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("marketplace", sa.String(length=32), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=True),
        sa.Column("external_id", sa.String(length=128), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("update_interval", sa.Integer(), nullable=True),
        sa.Column("last_scraped_at", sa.DateTime(), nullable=True),
        sa.Column("next_run_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_index(
        op.f("ix_tracked_products_canonical_url"),
        "tracked_products",
        ["canonical_url"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tracked_products_external_id"),
        "tracked_products",
        ["external_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tracked_products_marketplace"),
        "tracked_products",
        ["marketplace"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tracked_products_user_id"),
        "tracked_products",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "ai_insights",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("snapshot_count", sa.Integer(), nullable=False),
        sa.Column("window_days", sa.Integer(), nullable=False),
        sa.Column("last_price", sa.Float(), nullable=True),
        sa.Column("min_price", sa.Float(), nullable=True),
        sa.Column("max_price", sa.Float(), nullable=True),
        sa.Column("avg_price", sa.Float(), nullable=True),
        sa.Column("volatility", sa.Float(), nullable=True),
        sa.Column("slope", sa.Float(), nullable=True),
        sa.Column("pct_change_7d", sa.Float(), nullable=True),
        sa.Column("pct_change_30d", sa.Float(), nullable=True),
        sa.Column("trend", sa.String(length=32), nullable=False),
        sa.Column("anomaly", sa.String(length=32), nullable=False),
        sa.Column("recommendation", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("suggested_alert_price", sa.Float(), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"], ["tracked_products.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ai_insights_id"), "ai_insights", ["id"], unique=False)
    op.create_index(
        "ix_ai_insights_product_created",
        "ai_insights",
        ["product_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_insights_product_id"), "ai_insights", ["product_id"], unique=False
    )
    op.create_table(
        "price_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("marketplace", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("target_price", sa.Numeric(), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("triggered", sa.Boolean(), nullable=False),
        sa.Column("triggered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged", sa.Boolean(), nullable=False),
        sa.Column("ack_source", sa.String(), nullable=True),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["tracked_products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_index(op.f("ix_price_events_id"), "price_events", ["id"], unique=False)
    op.create_table(
        "price_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tracked_product_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("raw_price_text", sa.Text(), nullable=True),
        sa.Column("availability", sa.String(length=32), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tracked_product_id"], ["tracked_products.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_price_snapshots_tracked_product_id"),
        "price_snapshots",
        ["tracked_product_id"],
        unique=False,
    )

    op.execute(
        """
        CREATE OR REPLACE FUNCTION validate_product_url() RETURNS trigger AS $$
        BEGIN
            IF NEW.marketplace = 'amazon' AND NEW.url !~ '^https://www\.amazon\..+/dp/[A-Z0-9]{10}.*$' THEN
                RAISE EXCEPTION 'Invalid Amazon URL format. Must be: https://www.amazon.com';
            END IF;
            NEW.canonical_url := NEW.url;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;

        DROP TRIGGER IF EXISTS check_product_url_format ON tracked_products;
        CREATE TRIGGER check_product_url_format
        BEFORE INSERT OR UPDATE ON tracked_products
        FOR EACH ROW EXECUTE FUNCTION validate_product_url();
    """
    )


# ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_price_snapshots_tracked_product_id"), table_name="price_snapshots"
    )
    op.drop_table("price_snapshots")
    op.drop_index(op.f("ix_price_events_id"), table_name="price_events")
    op.drop_table("price_events")
    op.drop_index(op.f("ix_ai_insights_product_id"), table_name="ai_insights")
    op.drop_index("ix_ai_insights_product_created", table_name="ai_insights")
    op.drop_index(op.f("ix_ai_insights_id"), table_name="ai_insights")
    op.drop_table("ai_insights")
    op.drop_index(op.f("ix_tracked_products_user_id"), table_name="tracked_products")
    op.drop_index(
        op.f("ix_tracked_products_marketplace"), table_name="tracked_products"
    )
    op.drop_index(
        op.f("ix_tracked_products_external_id"), table_name="tracked_products"
    )
    op.drop_index(
        op.f("ix_tracked_products_canonical_url"), table_name="tracked_products"
    )
    op.drop_table("tracked_products")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
