"""add product_id to price_events

Revision ID: 5d23a9b3913e
Revises: 0f1b070fe3c3
Create Date: 2026-01-29 23:41:06.192585

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5d23a9b3913e"
down_revision: Union[str, Sequence[str], None] = "0f1b070fe3c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("price_events", sa.Column("product_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        None, "price_events", "tracked_products", ["product_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "price_events", type_="foreignkey")
    op.drop_column("price_events", "product_id")
    # ### end Alembic commands ###
